; ллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллл
; This file defines all the controls in the calc display
; copyright David B. Sher 2011
; ллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллл

NUMERATOR EQU 200
DENOMINATOR EQU 250
REALEDITOR EQU 202
ENTERBUTTON EQU 300
POPBUTTON EQU 310
ADDBUTTON EQU 350
SUBTRACTBUTTON EQU 360
MULTIPLYBUTTON EQU 370
DIVIDEBUTTON   EQU 380
SQRTBUTTON EQU 351
REALMODE EQU 301
FRACMODE EQU 303
FRACCALC EQU 100



